[[libportaudio]]
arch = "aarch64"
git-tree-sha1 = "1a6f2a76bd57a01205e00cf7fab2bb19d4717c3c"
os = "macos"

    [[libportaudio.download]]
    sha256 = "49fa60cae701881f373f28149ef9ff8e934e2105082acf3e7d9b6a017a512ad5"
    url = "https://github.com/anandijain/libportaudio_jll.jl/releases/download/libportaudio-v19.7.0+0/libportaudio.v19.7.0.aarch64-apple-darwin.tar.gz"
